-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.Object.CategoryType exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shops.InputObject
import Shops.Interface
import Shops.Object
import Shops.Scalar
import Shops.ScalarCodecs
import Shops.Union


{-| -}
id : SelectionSet Shops.ScalarCodecs.Id Shops.Object.CategoryType
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shops.ScalarCodecs.codecs |> Shops.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
name : SelectionSet String Shops.Object.CategoryType
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| -}
slug : SelectionSet String Shops.Object.CategoryType
slug =
    Object.selectionForField "String" "slug" [] Decode.string


{-| -}
products :
    SelectionSet decodesTo Shops.Object.ProductType
    -> SelectionSet (List decodesTo) Shops.Object.CategoryType
products object_ =
    Object.selectionForCompositeField "products" [] object_ (identity >> Decode.list)
