-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.Object.CustomerType exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shops.InputObject
import Shops.Interface
import Shops.Object
import Shops.Scalar
import Shops.ScalarCodecs
import Shops.Union


{-| -}
id : SelectionSet Shops.ScalarCodecs.Id Shops.Object.CustomerType
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shops.ScalarCodecs.codecs |> Shops.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
wallet :
    SelectionSet decodesTo Shops.Object.WalletType
    -> SelectionSet decodesTo Shops.Object.CustomerType
wallet object_ =
    Object.selectionForCompositeField "wallet" [] object_ identity


{-| -}
shopSet :
    SelectionSet decodesTo Shops.Object.ShopType
    -> SelectionSet (List decodesTo) Shops.Object.CustomerType
shopSet object_ =
    Object.selectionForCompositeField "shopSet" [] object_ (identity >> Decode.list)
