-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.Object.ProductType exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shops.InputObject
import Shops.Interface
import Shops.Object
import Shops.Scalar
import Shops.ScalarCodecs
import Shops.Union


{-| -}
id : SelectionSet Shops.ScalarCodecs.Id Shops.Object.ProductType
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shops.ScalarCodecs.codecs |> Shops.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
name : SelectionSet String Shops.Object.ProductType
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| -}
slug : SelectionSet String Shops.Object.ProductType
slug =
    Object.selectionForField "String" "slug" [] Decode.string


{-| -}
stock : SelectionSet Int Shops.Object.ProductType
stock =
    Object.selectionForField "Int" "stock" [] Decode.int


{-| -}
price : SelectionSet Int Shops.Object.ProductType
price =
    Object.selectionForField "Int" "price" [] Decode.int


{-| -}
shop :
    SelectionSet decodesTo Shops.Object.ShopType
    -> SelectionSet decodesTo Shops.Object.ProductType
shop object_ =
    Object.selectionForCompositeField "shop" [] object_ identity


{-| -}
category :
    SelectionSet decodesTo Shops.Object.CategoryType
    -> SelectionSet decodesTo Shops.Object.ProductType
category object_ =
    Object.selectionForCompositeField "category" [] object_ identity
