-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.Object.ShopType exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Shops.InputObject
import Shops.Interface
import Shops.Object
import Shops.Scalar
import Shops.ScalarCodecs
import Shops.Union


{-| -}
id : SelectionSet Shops.ScalarCodecs.Id Shops.Object.ShopType
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Shops.ScalarCodecs.codecs |> Shops.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
name : SelectionSet String Shops.Object.ShopType
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| -}
slug : SelectionSet String Shops.Object.ShopType
slug =
    Object.selectionForField "String" "slug" [] Decode.string


{-| -}
wallet :
    SelectionSet decodesTo Shops.Object.WalletType
    -> SelectionSet decodesTo Shops.Object.ShopType
wallet object_ =
    Object.selectionForCompositeField "wallet" [] object_ identity


{-| -}
holders :
    SelectionSet decodesTo Shops.Object.CustomerType
    -> SelectionSet (List decodesTo) Shops.Object.ShopType
holders object_ =
    Object.selectionForCompositeField "holders" [] object_ (identity >> Decode.list)


{-| -}
products :
    SelectionSet decodesTo Shops.Object.ProductType
    -> SelectionSet (List decodesTo) Shops.Object.ShopType
products object_ =
    Object.selectionForCompositeField "products" [] object_ (identity >> Decode.list)
