-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import Shops.InputObject
import Shops.Interface
import Shops.Object
import Shops.Scalar
import Shops.ScalarCodecs
import Shops.Union


type alias PostProductRequiredArguments =
    { name : String
    , price : Int
    , shopId : Shops.ScalarCodecs.Id
    , slug : String
    , stock : Int
    }


postProduct :
    PostProductRequiredArguments
    -> SelectionSet decodesTo Shops.Object.ProductMutation
    -> SelectionSet (Maybe decodesTo) RootMutation
postProduct requiredArgs object_ =
    Object.selectionForCompositeField "postProduct" [ Argument.required "name" requiredArgs.name Encode.string, Argument.required "price" requiredArgs.price Encode.int, Argument.required "shopId" requiredArgs.shopId (Shops.ScalarCodecs.codecs |> Shops.Scalar.unwrapEncoder .codecId), Argument.required "slug" requiredArgs.slug Encode.string, Argument.required "stock" requiredArgs.stock Encode.int ] object_ (identity >> Decode.nullable)


type alias PostShopRequiredArguments =
    { name : String
    , slug : String
    }


postShop :
    PostShopRequiredArguments
    -> SelectionSet decodesTo Shops.Object.ShopMutation
    -> SelectionSet (Maybe decodesTo) RootMutation
postShop requiredArgs object_ =
    Object.selectionForCompositeField "postShop" [ Argument.required "name" requiredArgs.name Encode.string, Argument.required "slug" requiredArgs.slug Encode.string ] object_ (identity >> Decode.nullable)


type alias BuyProductRequiredArguments =
    { id : Shops.ScalarCodecs.Id }


buyProduct :
    BuyProductRequiredArguments
    -> SelectionSet decodesTo Shops.Object.BuyProductMutation
    -> SelectionSet (Maybe decodesTo) RootMutation
buyProduct requiredArgs object_ =
    Object.selectionForCompositeField "buyProduct" [ Argument.required "id" requiredArgs.id (Shops.ScalarCodecs.codecs |> Shops.Scalar.unwrapEncoder .codecId) ] object_ (identity >> Decode.nullable)
