-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.Object exposing (..)


type CategoryType
    = CategoryType


type CustomerType
    = CustomerType


type ProductType
    = ProductType


type ShopType
    = ShopType


type WalletType
    = WalletType
