-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import Shops.Scalar exposing (defaultCodecs)


type alias Id =
    Shops.Scalar.Id


codecs : Shops.Scalar.Codecs Id
codecs =
    Shops.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
