-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Shops.VerifyScalarCodecs exposing (..)


placeholder : String
placeholder =
    ""
